#!/usr/bin/python3
import sys


def factorize(n):
    i = 2
    if n < 2:
        return

    while n % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(n, n / i, i))


if len(sys.argv) != 2:
    print("Usage: python factors.py <file>")
    sys.exit(1)

try:
    with open(sys.argv[1]) as file:
        line = file.readline()

        while line != "":
            num = int(line.split('\n')[0])
            factorize(num)
            line = file.readline()
except:
    pass
